services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=warehouse'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=testuser'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
volumes:
  postgres:
